apiVersion: v1
kind: Service
metadata:
  name: nof-service-internal
  namespace: nof-apps
  labels:
    app.kubernetes.io/component: internal-service
    app.kubernetes.io/name: nof-service
    nof.forgath.ru/legacy-target: dragon-forge-internal
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      protocol: TCP
      targetPort: http
  selector:
    app.kubernetes.io/instance: dragon-forge
    app.kubernetes.io/name: dragon-forge
