apiVersion: v1
kind: ConfigMap
metadata:
  name: portal-gateway-config
  namespace: nof-apps
data:
  default.conf: |
    server {
      listen 80;
      server_name forgath.ru;

      location / {
        proxy_pass http://nof-mp:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
      }
    }

    server {
      listen 80;
      server_name task-tracker.forgath.ru;

      location / {
        proxy_pass http://nof-tt:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
      }
    }

    server {
      listen 80;
      server_name habit-tracker.forgath.ru;

      location / {
        proxy_pass http://nof-ht:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
      }
    }
