apiVersion: v1
kind: ConfigMap
metadata:
  name: nof-ht-config
  namespace: nof-apps
data:
  NEXTAUTH_URL: {{ .Values.nextauthUrl | quote }}
  NEXT_PUBLIC_CANONICAL_URL: {{ .Values.canonicalUrl | quote }}
  NEXT_PUBLIC_TELEGRAM_BOT_USERNAME: {{ .Values.telegramBotUsername | quote }}
  NEXT_PUBLIC_TELEGRAM_BOT_ID: {{ .Values.telegramBotId | quote }}
  NEXT_PUBLIC_APP_VERSION: {{ .Values.appVersion | quote }}
